## K Nearest Neighbors - KNN Python Lecture

Hi Guys,<br>

Welcome to the K Nearest Neighbors with Python lecture. <br>

After the theory lecture, its time to learn by doing. <br>
Let's create a situation here, this time you got the data which is highly confidential! <br>
Your client does not want to disclose the hidden features (dimensions). All the features are coded with some numbers. So far, based on the combination of different feature's code, your client makes the decisions.<br>
Data is growing and your client wants to automate the process. You are give a task to use the coded data along with the target class in 'Results' column and help your client in decision making. <br>
You decide to go with the KNN and create a model that predicts the target class for the new customers. <br>
**Great, let's explore!**<br>

First thing first, let's imports the libraries that we need!

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#%matplotlib inline

# Lines below are just to ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [30]:
df = pd.read_csv("Coded_Data.csv")
df

,Unnamed: 0,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10,Result
0,1,53.1,63.4,33.0,46.2,47.3,21.2,44.3,36.1,46.6,65.0,Y
1,2,36.9,54.7,31.1,50.5,56.0,38.9,39.4,56.8,33.0,78.8,N
2,3,41.9,65.5,53.5,52.3,92.5,43.2,94.9,64.7,50.8,67.9,N
3,4,71.7,75.6,37.9,50.5,69.2,52.5,82.3,77.3,80.8,60.9,Y
4,5,74.3,51.8,36.4,40.9,74.7,42.2,65.1,36.2,77.6,74.9,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,58.7,56.4,49.5,38.1,62.8,35.2,43.6,17.9,59.3,71.2,Y
996,997,33.4,52.1,54.7,48.5,85.7,76.2,61.6,40.0,50.8,87.8,N
997,998,66.0,53.6,45.4,56.1,54.6,53.1,22.6,21.8,48.8,73.2,Y
998,999,63.0,47.0,23.6,40.7,97.5,56.6,50.0,59.4,67.7,62.7,Y
999,1000,48.6,52.4,24.2,48.9,56.6,25.5,45.4,50.9,66.7,72.1,Y

In our dataframe, the first column looks like the index, let's set `index_col = 0`

In [2]:
df = pd.read_csv("Coded_Data.csv",index_col=0)
df

NameError: name 'pd' is not defined

Great, this looks fine now!<br>

Let's overview the data, we can use `info()` here!

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cd_1    1000 non-null   float64
 1   Cd_2    1000 non-null   float64
 2   Cd_3    1000 non-null   float64
 3   Cd_4    1000 non-null   float64
 4   Cd_5    1000 non-null   float64
 5   Cd_6    1000 non-null   float64
 6   Cd_7    1000 non-null   float64
 7   Cd_8    1000 non-null   float64
 8   Cd_9    1000 non-null   float64
 9   Cd_10   1000 non-null   float64
 10  Result  1000 non-null   object
dtypes: float64(10), object(1)
memory usage: 93.8+ KB

Let's split the data so that we can fit the `scaler` to the features only!

In [35]:
#features and results/target
target = df['Result']
features = df.drop('Result',axis=1)

In [36]:
df

      Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
1     53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
2     36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
3     41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
4     71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
5     74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
996   58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
997   33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
998   66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
999   63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
1000  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

In [39]:
features.head()

   Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10
1  53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0
2  36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8
3  41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9
4  71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9
5  74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9

In [8]:
target.head()

1    Y
2    N
3    N
4    Y
5    Y
Name: Result, dtype: object

Let's fit `scaler` to the features now!

In [9]:
# Importing
from sklearn.preprocessing import StandardScaler
# Creating instance 'scaler'
scaler = StandardScaler()

In [40]:
# We can do this in a one line as well!
#scaler.fit(df.drop('Result',axis=1))
scaler.fit(features)

StandardScaler()

So, we have the fitted features to the `scaler` object. We will use this `scaler` object to transform all the features using `.transform()` method in `Scikit-learn` to do the `standardization` job by centering and scaling.<br>
Let's pass the features to `scaler.transform()` to get standardized features in `scaled_features`!

In [41]:
scaled_features = scaler.transform(features)

In [42]:
type(scaled_features)

numpy.ndarray

In [43]:
scaled_features

array([[-0.12252539,  0.1875694 , -0.91183199, ..., -1.48006982,
        -0.95256187, -0.64536551],
       [-1.08602779, -0.43340316, -1.02415132, ..., -0.20055606,
        -1.82621843,  0.6351032 ],
       [-0.78865051,  0.33745933,  0.30003449, ...,  0.28776079,
        -0.68275617, -0.3762815 ],
       ...,
       [ 0.64470801, -0.51191693, -0.17880055, ..., -2.36398512,
        -0.81123508,  0.11549271],
       [ 0.46628164, -0.98299956, -1.46751711, ..., -0.03984418,
         0.40289057, -0.85877696],
       [-0.39016495, -0.59756832, -1.43204784, ..., -0.56524838,
         0.33865112,  0.01342636]], shape=(1000, 10))

`scaled_features` is a NumPy array, Let's convert this into the pandas `DataFrame`!<br>
We can use our `df.columns` to get the columns name and pass that to `DatFrame()` along with `scaled_features`, note we don't need `Results` column, [:-1] will work *(everything but the last one)*!

In [36]:
#Before Scaling
df.head()

   Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
1  53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
2  36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
3  41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
4  71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
5  74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y

In [44]:
cols = df.columns[:-1]
cols

Index(['Cd_1', 'Cd_2', 'Cd_3', 'Cd_4', 'Cd_5', 'Cd_6', 'Cd_7', 'Cd_8', 'Cd_9',
       'Cd_10'],
      dtype='object')

In [45]:
#After Scaling
df_scaled_features = pd.DataFrame(scaled_features, columns=cols)#df.columns[:-1])
df_scaled_features

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
0,-0.122525,0.187569,-0.911832,0.318653,-1.035516,-2.305940,-0.801865,-1.480070,-0.952562,-0.645366
1,-1.086028,-0.433403,-1.024151,0.624941,-0.445471,-1.153296,-1.131088,-0.200556,-1.826218,0.635103
2,-0.788651,0.337459,0.300034,0.753154,2.030007,-0.873275,2.597862,0.287761,-0.682756,-0.376282
3,0.983718,1.058359,-0.622166,0.624941,0.449771,-0.267648,1.751290,1.066595,1.244427,-1.025795
4,1.138354,-0.640394,-0.710839,-0.058864,0.822788,-0.938396,0.595651,-1.473889,1.038861,0.273232
...,...,...,...,...,...,...,...,...,...,...
995,0.210537,-0.312064,0.063573,-0.258307,0.015714,-1.394244,-0.848897,-2.605053,-0.136721,-0.070082
996,-1.294192,-0.618981,0.370973,0.482481,1.568822,1.275723,0.360492,-1.239002,-0.682756,1.470191
997,0.644708,-0.511917,-0.178801,1.023827,-0.540420,-0.228575,-2.259851,-2.363985,-0.811235,0.115493
998,0.466282,-0.983000,-1.467517,-0.073110,2.369113,-0.000651,-0.418892,-0.039844,0.402891,-0.858777
999,-0.390165,-0.597568,-1.432048,0.510973,-0.404778,-2.025919,-0.727958,-0.565248,0.338651,0.013426

<br>Our data is ready for the Machine Learning part now!
## Let's do the train_test split 
I am sure, you are very comfortable with this now!

In [36]:
from sklearn.model_selection import train_test_split

In [46]:
X = scaled_features
y = target

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)


#keep the test_size and random_state same if you want to have the 
#same results as mine!

In [47]:
X_train

array([[ 0.50196691, -0.09793522,  0.80842726, ..., -0.40453651,
         1.3857542 , -1.76809532],
       [-1.20497871,  1.74356961,  0.23500751, ...,  0.26303589,
        -1.38939015, -0.71031682],
       [-0.81244069,  0.75144104, -0.52758164, ...,  0.80698377,
         0.92965408, -0.03296743],
       ...,
       [-0.8005456 ,  1.30103744,  0.68428484, ..., -0.46634877,
        -1.09388867,  1.45163398],
       [ 1.66768587, -0.65466924,  1.10400445, ..., -1.12155871,
         1.66840779,  0.17116526],
       [-1.24661153,  0.52303734,  1.1512968 , ...,  0.65245312,
        -1.38939015,  0.31034664]], shape=(700, 10))

In [48]:
y_train

243    Y
688    N
681    Y
235    Y
767    N
      ..
380    Y
710    N
232    N
316    Y
400    N
Name: Result, Length: 700, dtype: object

## KNN
Our focus is to come up with a model that can predict the class in `Result` for the new data point. We don't know what k number will work best, let's start with k = 1 at the moment. <br>
We need to import the `KNeighborsClassifier` from `sklearn.neighbors`.

In [49]:
from sklearn.neighbors import KNeighborsClassifier

Let's Create a KNN model instance with n_neighbors=1

In [46]:
knn = KNeighborsClassifier(n_neighbors=3) 
#shift+tab to see the other options, we will only use n_neighbors

Let's fit this model to the training data, You know this all now!

In [50]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Let's do the predictions now!

In [51]:
predictions = knn.predict(X_test)
predictions

array(['N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y',
       'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N',
       'N', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N',
       'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y'], dtype=object)

In [52]:
knn.score(X_test, y_test)

0.93

In [53]:
knn.predict([[-1.122525, 0.187569, -0.911832, 0.318653, -0.035516, -0.305940, -0.801865, -1.480070, -0.952562, -2.645366]])

array(['Y'], dtype=object)

## Evaluation
As we already know, the evaluation is very important to know if the model is working fine or not! <br>
Let's see how the confusion matrix and classification report look like!

In [50]:
from sklearn.metrics import classification_report,confusion_matrix

In [54]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test,predictions))

[[122  17]
 [  4 157]]
              precision    recall  f1-score   support

           N       0.97      0.88      0.92       139
           Y       0.90      0.98      0.94       161

    accuracy                           0.93       300
   macro avg       0.94      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300

So, it was worth finding the optimum value for k, our model is performing better. 
## Great Job!
Let's move on to the project exercise now to practice the skills in knn!